# Generated by Django 5.2.4 on 2025-07-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Humedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humedad_actual', models.CharField(max_length=10)),
                ('humedad_maxima', models.CharField(max_length=10)),
                ('humedad_minima', models.CharField(max_length=10)),
                ('humedad_solicitada', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Luz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luz_actual', models.CharField(max_length=10)),
                ('luz_maxima', models.CharField(max_length=10)),
                ('luz_minima', models.CharField(max_length=10)),
                ('luz_solicitada', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura_actual', models.CharField(max_length=10)),
                ('temperatura_maxima', models.CharField(max_length=10)),
                ('temperatura_minima', models.CharField(max_length=10)),
                ('temperatura_solicitada', models.CharField(max_length=10)),
            ],
        ),
    ]
