# Generated by Django 5.2.4 on 2025-07-04 22:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='adminGestio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechas', models.DateTimeField(default=django.utils.timezone.now)),
                ('Cantidad_Productos', models.CharField(max_length=10)),
                ('tipo_Cosecha', models.CharField(choices=[('Cosecha Manual', 'Cosecha Manual'), ('Cosecha Mecanica', 'Cosecha Mecanica')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='adminPerdidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(choices=[('Temporada 1', 'Temporada 1'), ('Temporada 2', 'Temporada 2'), ('Temporada 3', 'Temporada 3'), ('Temporada 4', 'Temporada 4')], max_length=100)),
                ('cantidadPerdidas', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='admInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Semillas', models.CharField(choices=[('Alverja', 'Alverja'), ('Frijoles', 'Frijoles'), ('Cafe', 'Cafe'), ('Sandia', 'Sandia'), ('Papa', 'Papa'), ('Aguacate', 'Aguacate'), ('Tomate', 'Tomate'), ('Mora', 'Mora'), ('Papaya', 'Papaya'), ('Uvas', 'Uvas')], max_length=10)),
                ('CosechasRegistradas', models.CharField(choices=[('Finalizada', 'Finalizada'), ('En proceso', 'En porceso')], max_length=100)),
                ('PerdidaCosechas', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('tipoDocumento', models.CharField(choices=[('Tarjeta de Identidad', 'T.I'), ('Cedula de Ciudadania', 'C.C')], max_length=100)),
                ('numeroDocumento', models.CharField(max_length=10)),
                ('contraseña', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='reportesadministrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporte', models.CharField(choices=[('Activos', 'Activo'), ('Pasivos', 'Pasivo'), ('Ganancias', 'Ganancia')], max_length=100)),
                ('temporada', models.CharField(choices=[('Temporada 1', 'Temporada 1'), ('Temporada 2', 'Temporada 2'), ('Temporada 3', 'Temporada 3'), ('Temporada 4', 'Temporada 4')], max_length=100)),
                ('cantidadReporte', models.CharField(max_length=100000000)),
            ],
        ),
        migrations.CreateModel(
            name='semillaTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoSemilla', models.CharField(choices=[('Alverja', 'Alverja'), ('Frijoles', 'Frijoles'), ('Cafe', 'Cafe'), ('Sandia', 'Sandia'), ('Papa', 'Papa'), ('Aguacate', 'Aguacate'), ('Tomate', 'Tomate'), ('Mora', 'Mora'), ('Papaya', 'Papaya'), ('Uvas', 'Uvas')], max_length=100)),
                ('cantidad', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='invetarioCosecha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(choices=[('Temporada 1', 'Temporada 1'), ('Temporada 2', 'Temporada 2'), ('Temporada 3', 'Temporada 3'), ('Temporada 4', 'Temporada 4')], max_length=100)),
                ('tipo_cosecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app3miguelysantiago.adminventario')),
            ],
        ),
        migrations.CreateModel(
            name='InicioSecion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('Agricultor', 'Agricultor'), ('Administrador', 'Administrador')], max_length=20)),
                ('numeroDoc', models.CharField(max_length=10)),
                ('contraseña', models.ForeignKey(max_length=15, on_delete=django.db.models.deletion.CASCADE, to='app3miguelysantiago.registro')),
            ],
        ),
    ]
