# Generated by Django 5.2.4 on 2025-07-04 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agricultor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CientificoDeDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(max_length=255)),
                ('fecha_siembra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='DatoClimatico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('humedad', models.FloatField()),
                ('lluvia', models.FloatField()),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datos_climaticos', to='app2frankyjoner.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='ModeloPredictivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modelo', models.CharField(max_length=100)),
                ('fecha_entrenamiento', models.DateField()),
                ('cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2frankyjoner.cultivo')),
            ],
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(max_length=100)),
                ('nivel_alerta', models.CharField(max_length=50)),
                ('fecha_generacion', models.DateTimeField()),
                ('modelo_predictivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='app2frankyjoner.modelopredictivo')),
            ],
        ),
        migrations.CreateModel(
            name='Recomendacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cultivo_asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='app2frankyjoner.cultivo')),
            ],
        ),
    ]
