# Generated by Django 5.2.4 on 2025-07-04 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstandarCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('parametro', models.CharField(max_length=100)),
                ('valor_minimo', models.FloatField()),
                ('valor_maximo', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoteGrano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_lote', models.CharField(max_length=50, unique=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('tipo_grano', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MedicionCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametro', models.CharField(max_length=100)),
                ('valor_medido', models.FloatField()),
                ('cumple_estandar', models.BooleanField(null=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app9maicolybrayant.lotegrano')),
            ],
        ),
    ]
